version: '3'
services:
  relaxAPI:
    image: azipis/relaxapi:latest
    container_name: relaxAPI
    build:
      context: ./docker
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    networks:
      - plnet
      - canarynet
networks:
  plnet:
    name: plnet
    driver: bridge
    external: true
  canarynet:
    name: canarynet
    driver: bridge
    external: true
